version: '3'
services:

  web:
    image: killrvideo/killrvideo-web:3.0.0-rc1
    ports:
      - "3000:3000"
    depends_on:
      - dse
      - backend
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug
    labels:
      kompose.service.type: nodeport

  backend:
    image: killrvideo/killrvideo-nodejs:3.0.0-rc2
    ports:
      - "50101:50101"
    depends_on:
      - dse
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug

  studio:
    image: datastax/dse-studio:6.7.0
    ports:
      - "9091:9091"
    depends_on:
      - dse
    environment:
      DS_LICENSE: accept
    labels:
      kompose.service.type: nodeport

  dse:
    image: datastax/dse-server:6.7.0
    command: [ -s -g ]
    ports:
      - "9042:9042"
      - "8983:8983"
      - "8182:8182"
    environment:
      DS_LICENSE: accept
    # Allow DSE to lock memory with mlock
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1

  dse-config:
    image: killrvideo/killrvideo-dse-config:2.2.1
    environment:
      KILLRVIDEO_SERVICE_DISCOVERY_DISABLED: 'true'
    depends_on:
      - dse
    restart: on-failure

  generator:
    image: killrvideo/killrvideo-generator:3.0.0-rc4
    depends_on:
      - dse
      - backend
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug

#  opscenter:
#    image: datastax/dse-opscenter:6.5.0
#    ports:
#    - "8888:8888"
#    environment:
#      DS_LICENSE: accept
