apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
  - name: "50101"
    port: 50101
    targetPort: 50101
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
