apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - env:
        - name: KILLRVIDEO_DSE_CONTACT_POINTS
          value: dse
        - name: KILLRVIDEO_LOGGING_LEVEL
          value: debug
        image: killrvideo/killrvideo-java:3.0.1
        imagePullPolicy: ""
        name: backend
        ports:
        - containerPort: 50101
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
