apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dse-config
  name: dse-config
spec:
  containers:
  - env:
    - name: KILLRVIDEO_SERVICE_DISCOVERY_DISABLED
      value: "true"
    image: killrvideo/killrvideo-dse-config:2.2.2-rc2
    name: dse-config
    resources: {}
  restartPolicy: OnFailure
status: {}
