apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dse-config
  name: dse-config
spec:
  containers:
  - image: killrvideo/killrvideo-dse-config:3.0.0-rc1
    name: dse-config
    resources: {}
  restartPolicy: OnFailure
status: {}
