apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: generator
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: generator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: generator
    spec:
      containers:
      - env:
        - name: KILLRVIDEO_LOGGING_LEVEL
          value: debug
        image: killrvideo/killrvideo-generator:3
        imagePullPolicy: ""
        name: generator
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
