apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.service.type: nodeport
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: studio
  name: studio
spec:
  ports:
  - name: "9091"
    port: 9091
    targetPort: 9091
  selector:
    io.kompose.service: studio
  type: NodePort
status:
  loadBalancer: {}
